[id="module-load",reftext="`module load|unload`"]
= Load and unloading a module
== NAME

`module add|load` - load modules +
`module rm|unload` - unload modules

== SYNOPSIS

`module add [OPTIONS] modulefile...` +
`module load [OPTIONS] modulefile...` +
`module rm modulefile...` +
`module unload modulefile...`

== DESCRIPTION

Load modulefile(s) into shell environment. Loading a group-head will extend the `MODULEPATH`. E.g.: loading a compiler makes additional modules like openmpi and other libraries/packages compiled with this compiler available.

If you try to load a module which is not available in the current `MODULEPATH` but installed in the module hierarchy, a message will be printed showing prerequisite modules.

If you load a deprecated or unstable module, a warning will be printed.

You can change the verbosity of the load sub-command by setting the environment variable `PMODULES_VERBOSITY` to silent, warn or verbose.

silent::  Print error messages only. 
warn::    Print a warning message, when loading a deprecated or unstable module. 
verbose:: Print warning messages and print prerequisite modules if the module to load is not available, but installed in hierarchy.


== OPTIONS / FLAGS

`-f | --force`:: Force active dependency resolution. This will result in modules found on a prereq command inside a module file being load automatically. Unloading module files using this switch will result in all required modules which have been loaded automatically using the -f switch being unload. This switch is experimental at the moment. 

`-v | --verbose`:: Set verbosity level to verbose. 

`-w | --warn`:: Set verbosity level to warn. 

`-s | --silent`:: Set verbosity level to silent. 

== EXAMPLES (add|load)

Loading the modules `gcc/4.9.2`, `openmpi/1.8.4` and `hdf5/1.8.14`:

-----
$ module load gcc/4.9.2
$ module load openmpi/1.8.4
$ module load hdf5/1.8.14
$ module list 
Currently Loaded Modulefiles:
  1) gcc/4.9.2       2) openmpi/1.8.4   3) hdf5/1.8.14
-----

or

-----
$ module load gcc/4.9.2 openmpi/1.8.4 hdf5/1.8.14
-----

If you try to load `hdf5/1.8.14` without the prerequisite modules, some "hints" will be printed, if the default verbosity level is set:

-----
$ module purge
$ module load hdf5/1.8.14 
The module 'hdf5/1.8.14' cannot be loaded!
Try with one of the following command(s):

module load gcc/4.7.4 openmpi/1.6.5 hdf5/1.8.14
module load gcc/4.7.4 openmpi/1.8.2 hdf5/1.8.14
module load gcc/4.7.4 openmpi/1.8.4 hdf5/1.8.14
module load gcc/4.8.3 openmpi/1.6.5 hdf5/1.8.14
module use deprecated; module load gcc/4.8.3 openmpi/1.8.2 hdf5/1.8.14
module use deprecated; module load gcc/4.8.3 openmpi/1.8.4 hdf5/1.8.14
module load gcc/4.8.4 openmpi/1.6.5 hdf5/1.8.14
module use deprecated; module load gcc/4.8.4 openmpi/1.8.2 hdf5/1.8.14
module use deprecated; module load gcc/4.8.4 openmpi/1.8.4 hdf5/1.8.14
module use deprecated; module load gcc/4.8.4 openmpi/1.8.8 hdf5/1.8.14
module use deprecated; module load gcc/4.9.2 openmpi/1.6.5 hdf5/1.8.14
module use deprecated; module load gcc/4.9.2 openmpi/1.8.2 hdf5/1.8.14
module use deprecated; module load gcc/4.9.2 openmpi/1.8.4 hdf5/1.8.14
-----

Use verbosity level `warn` to suppress the hints:

-----
$ module load hdf5/1.8.14 --warn
module load: module unavailable -- hdf5/1.8.14
-----

Loading an unstable module:

-----
$ module use unstable
$ module load cmake/3.1.3 
Warning: the unstable module 'cmake/3.1.3' has been loaded.
-----

To supress the warning, use the `--silent` option.

== EXAMPLES (rm|unload)

-----
$ module list 
Currently Loaded Modulefiles:
  1) gcc/4.9.2       2) openmpi/1.8.4   3) hdf5/1.8.14
$ module rm openmpi/1.8.4 
$ module list 
Currently Loaded Modulefiles:
  1) gcc/4.9.2
-----

The module `hdf5/1.8.14` is unloaded as a dependency of `openmpi/1.8.4`.

== SEE ALSO

<<module-use>>, <<module-load>>, <<module-purge>>, <<module-swap>>, <<module-list>>
