= *TUTORIALS*

== Step-by-step guide to build a 'Hello, world!' module

1. Download a stub for a new build-block
+
[source,shell]
----
wget --output-document=stub.tgz https://github.com/Pmodules/buildblock_stub/archive/refs/tags/1.0.0.tar.gz 
----
1. Unpack the stub into the directory `hello_world`
+
[source,shell]
----
mkdir hello_world
tar --strip-components 1 -xvf ../stub.tgz
chmod 0755 build
----
1. Edit `files/config.yaml`
+
[source,yaml]
----
format: 1
hello_world:                           # <1>
  defaults:                            # <2>
    group: Tools                       # <3>
    relstage: stable                   # <4>
    systems: [.*]                      # <5>
    docfiles: [LICENSE]
    compile_in_sourcetree: true        # <6>
    urls:                              # <7>
      - url: https://github.com/Pmodules/$P/archive/refs/tags/$V.tar.gz 
        name: $P-$V.tar.gz

  shasums:                             # <8>
    hello_world-1.0.0.tar.gz: bc1cfd90ac55e9f3babab0a426ed4b3c7edf15266363ab1b595d234797fbce7b 

  versions:
    1.0.0:
      config:                          # <9>
        relstage: unstable             # <10>
----
+
<1> The name of the module.
<2> Default configuration for all version. This can be overwritten in the 'versions' section.
<3> The group the module will be installed in.
<4> If not otherwise specified in the version specific configuration, the release stage is set to `stable`.
<5> The module is available on all systems. Availability can be restricted to hostname patterns and/or OS/Linux distribution (like rhel8, sles15)
<6> Usually the software is compiled in a dedicated build directory. Here we have to compile in the source tree.
<7> Download URL and filename. `$P` will be substituted by the module name and `$V` by the version. 
<8> SHA256 hash sums for each source file.
<9> Configuration for version 1.0.0. 
<10> Overwrite the default release stage.

1. Edit the build script
+
[source,shell]
----
#!/usr/bin/env modbuild

pbuild::configure() {    # <1>
	:
}

pbuild::install() {      # <2>
	mkdir -p "${PREFIX}/bin"
	install --mode=0755 "${SRC_DIR}/hello_world" "${PREFIX}/bin"
}
----
<1> Don't use the default `pbuild::configure()`` function!
    There is nothing to configure. :)
<2> The Makefile doesn't have an 'install' target. Therefore we have to code it ourself. 


